Output img/demo.gif

Set Shell "bash"
Set FontSize 20
Set Width 1000
Set Height 380
Set Padding 15
Set TypingSpeed 60ms

Set Theme "Monokai Pro"

Type `todo add "Record a demo gif"`
Enter
Sleep 1.5s

Type `todo add 'Create todo CLI' Rust`
Enter
Sleep 2s

Hide
Type "clear"
Enter
Show

Type `todo use Rust`
Enter
Sleep 1.5s

Type `todo add 'Deploy v0.1.0'`
Enter
Sleep 1.5s

Type `todo done 1`
Enter
Sleep 1.5s

Hide
Type "clear"
Enter
Show

Type "todo use default"
Enter
Sleep 1.5s

Type "todo done 1"
Enter
Sleep 1.5s

Hide
Type "clear"
Enter
Show

Type "todo progress"
Enter
Sleep 2s